
// ----------------------------------------------------------------
// Language

class Language {
  constructor () {
    this.default = 'ja';
    this.en = {
      language_name: 'English',

      terms_of_service: `${Project.NAME} Terms of Service`,
      terms_welcome_header: `Welcome to the ${Project.NAME}`,

      privacy_policy: 'Privacy policy',

      please_feedback: 'Please give feedback to clipweb.',
      feedback_message: 'We are also looking for not only bug reports but also functions and impressions that I think are good.',
      feedback_received_data: 'Only feedback content will be sent to the clipweb administrator.',
      thank_you_feedback: 'Thank you for sending feedback.',

      user: 'User',
      username: 'Username',
      email_address: 'Email address',
      password: 'Password',
      password_hash: 'Password hash',
      crypto_hash: 'Crypto hash',
      last_search: 'Last search',
      last_search_type: 'Last type of search',
      last_search_group: 'Last group of search',
      last_search_sort: 'Last sort of search',
      history_clip: 'History of clip',
      language: 'Language',
      auto_login: 'Auto login',
      password_confirm: 'Confirm Password',
      new_password: 'New Password',
      avatar: 'Avatar',
      theme: 'Theme',
      default_owner_public: 'Default Owner public',
      default_clip_mode: 'Default clip mode',
      owner_public: 'Owner public',
      clip_mode: 'clip mode',
      using_gravatar: 'Using {gravatar}',

      filename: 'File name',
      filetype: 'File type',

      clip: 'clip',
      clips: 'clips',

      list: 'List',
      history: 'History',
      help: 'Help',

      status_login: 'Status of Login',
      terms_agree: 'Acceptance of Terms of Service',

      register: 'Register',
      login: 'Login',
      logout: 'Logout',
      setting: 'Setting',
      info: 'Info',

      license: 'License',
      column: 'Column',
      value: 'Value',
      none: 'None',
      all: 'All',
      open: 'Open',
      show: 'Show',
      view: 'View',
      unknown: 'Unknown',
      name: 'Name',
      yes: 'Yes',
      no: 'No',
      on: 'On',
      off: 'Off',
      save: 'Save',
      access: 'Access',
      new_create: 'New',
      clip_new_create: 'New clip',
      clip_info: 'clip info',
      share_list: 'Share list',
      privilege_users_list: 'Privilege user list',
      clip_history: 'clip history',
      start: 'Start',
      restart: 'Restart',
      initial: 'Initial',
      init: 'Init',
      reload: 'Reload',
      encryption: 'Encryption',
      update: 'Update',
      create: 'Create',
      new: 'New',
      edit: 'Edit',
      delete: 'Delete',
      accept: 'Accept',
      agree: 'I agree',
      close: 'Close',
      feedback: 'Feedback',
      report: 'Report',
      content: 'Content',
      send: 'Send',
      search: 'Search',
      search_string: 'Search string',
      search_query: 'Query',
      search_type: 'Type',
      group: 'Group',
      sort: 'Sort',
      type: 'Type',
      tag: 'Tag',
      tags: 'Tags',
      owner: 'Owner',
      created_at: 'Created date time',
      updated_at: 'Updated date time',
      private: 'Private',
      public: 'Public',
      share: 'Share',
      light: 'Light',
      dark: 'Dark',

      within_1_week: 'Within a week',
      within_1_month: 'Within a month',
      within_3_month: 'Within 3 months',
      within_6_month: 'Within 6 months',
      within_1_year: 'Within a year',
      over_1_year_ago: 'Over a year ago',

      header_user_register: 'Join clipweb',
      header_user_login: 'Login',
      header_user_logout: 'Logout',
      header_user_leaving: 'Leave clipweb',
      header_user_setting: 'User Setting',
      header_user_info: 'User Info',

      header_list_search: 'clip List',

      header_clip_new: 'New clip',
      header_clip_setting: 'clip setting',
      header_clip_privilege: 'clip privilege',
      header_clip_history: 'clip history',

      header_code_editor: null,

      loading_header_user_register: 'Registering to clipweb',
      loading_header_user_login: 'Login to clipweb',
      loading_header_user_logout: 'Logout from clipweb',
      loading_header_user_leaving: 'Leaving from clipweb',
      loading_header_user_setting: 'Saving your Setting',
      loading_header_user_info: 'Saving your Info',

      loading_header_list_search: 'Getting clip list',

      loading_header_clip_new: 'Creating the clip',
      loading_header_clip_load: 'Getting info of the clip',
      loading_header_clip_setting: 'Saving setting of the clip',
      loading_header_clip_privilege: 'Getting privilege of the clip',
      loading_header_clip_ban: 'Deleting privilege list of the clip',
      loading_header_clip_history: 'Getting history of the clip',
      loading_header_clip_delete: 'Deleting the clip',

      loading_header_code_load: 'Loading code of the clip',

      user_registered: 'Registered you.',
      user_logined: 'You logined.',
      user_logouted: 'You logouted.',
      user_update_info: 'Update your info.',
      user_update_setting: 'Update your setting.',

      clip_list_got: 'Got your clips.',
      created_new_clip: 'Created new clip.',
      updated_clip_setting: 'Updated clip setting.',
      deleted_clip: 'Deleted the clip.',
      shared_clip: 'Shared the clip.',
      stopped_share_to_user: 'Stopped share to {ban_username}.',

      saved_clip: 'Saved this clip.',
      downloaded_clip: 'Downloaded the clip.',

      please_email_auth: 'Please Email authentication.',
      userdata_clear: 'Delete your data',
      userdata_clear_confirm: 'Delete user data saved in the browser?',
      delete_clip: 'Delete the clip',
      delete_clip_confirm: 'Are you sure you want to delete the clip?',
      share_clip: 'Share the clip',
      share_clip_message: 'Please share this URL',
      share_clip_sns: 'It can be shared by SNS.',
      stop_share_user: 'Stop the share',
      stop_share_user_confirm: 'Do you want to stop sharing to this user?',
      concurrent_editing_stop: 'Pause simultaneous editing',
      close_to_start_concurrent_editing: 'Closing this screen resumes simultaneous editing.',

      copied: 'Copied',
      copied_share_link: 'Copied the share URL',

      need_login_to_share: 'Login is required to share.',
      please_all_inputs_correctly: 'Please enter all items correctly.',
      please_inputs_correctly: 'Please enter items correctly.',
      please_selects_correctly: 'Please select items correctly.',
      password_dont_match: 'Password don\'t match.',

      username_alreay_exist: 'Username already exists.',
      email_address_alreay_exist: 'Email address already exists.',
      hash_alreay_exist: 'User information can not be constructed. please try again.',
      email_password_incorrect: 'The combination of the e-mail address and the password is incorrect.',
      password_incorrect: 'Password is incorrect.',
      user_not_found: 'User data not found.',
      clip_not_exists: 'clip not found.',
      owner_not_exists: 'clip owner not exists.',
      corrupt_userdata: 'User data is corrupted. Please contact the administrator.',
      corrupt_clipdata: 'clip data is corrupted. Please contact the administrator.',
      permission_denied: 'Permission denied.',
      permission_denied_or_clip_not_found: 'Permission denied or clip does not exist.',
      failed_update_share: 'Failed to update share date.',

      failed_to_register: 'Failed to register.',
      failed_to_login: 'Failed to login.',
      failed_to_logout: 'Failed to logout.',
      failed_to_save_setting: 'Failed to save of user setting.',
      failed_to_save_info: 'Failed to save of user info.',

      failed_to_get_clip_list: 'Failed to getting your clips.',
      failed_to_create_new_clip: 'Failed to creating new clip.',

      failed_to_open_clip_setting: 'Failed to open setting of the clip.',
      failed_to_load_clip_setting: 'Failed to load setting of the clip.',
      failed_to_update_clip_setting: 'Failed to update setting of the clip.',
      failed_to_setting_clip_setting: 'Failed to update setting of the clip.',
      failed_to_load_clip_privilege: 'Failed to load privilege of the clip.',
      failed_to_load_clip_history: 'Failed to load history of the clip.',
      failed_to_delete_clip: 'Failed to delete the clip.',
      failed_to_get_share_clip: 'Failed to share the clip.',
      failed_to_stop_share: 'Failed to stop share.',

      failed_to_load_code: 'Failed to load the clip.',
      failed_to_save_code: 'Failed to save the clip.',
      failed_to_download_code: 'Failed to download the clip.',
      failed_to_sync_code: 'Failed to sync the clip.',
      failed_to_connect_chat: 'Failed to connect chat.',

      failed_connect_to_server: 'Failed connect to clipweb server.',
      server_not_working: 'clipweb server is not working properly.',

      popover_user_register_username: 'User name to register in clipweb<hr><div class="popover-center">Rule</div><div class="popover-item-title">Minimum number of characters</div>3 letters<br><div class="popover-item-title">Maximum number of characters</div>32 characters',
      popover_user_register_email: 'E-mail address to register for clipweb<hr><div class="popover-center">Rule</div><div class="popover-item-title">Format</div>Mail address format',
      popover_user_register_password: 'Password required at login<hr><div class="popover-center">Rule</div><div class="popover-item-title">Minimum number of characters</div>8 letters<br><div class="popover-item-title">Maximum number of characters</div>32 characters<br><div class="popover-item-title">Format</div>Including both alphabets and numbers.',
      popover_user_register_password_re: 'Please enter your password again.<hr><div class="popover-center">Rule</div><div class="popover-item-title">Format</div>Match Password',
      popover_user_login_email: 'E-mail address registered in clipweb',
      popover_user_login_password: 'Password registered in clipweb',
      popover_user_login_auto: 'When checked, log in automatically from this web browser.<hr><div class="popover-item-title">Note</div>Please do not use on a computer shared with family etc.',
      popover_user_logout_username: 'Your user name',
      popover_user_info_avatar: 'We use <a href="https://gravatar.com/" target="blank">Gravatar</a> for Avatar.<br>The avatar associated with the email address is displayed.',
      popover_user_info_username: 'You can change your user name.<hr><div class="popover-center">Rule</div><div class="popover-item-title">Minimum number of characters</div>3 letters<br><div class="popover-item-title">Maximum number of characters</div>32 characters',
      popover_user_info_email: 'You can change your email address.<hr><div class="popover-center">Rule</div><div class="popover-item-title">Format</div>Mail address format',
      popover_user_info_old_password: 'To change user information, password authentication is required.',
      popover_user_info_new_password: 'You can change the password required for login.<hr><div class="popover-center">Rule</div><div class="popover-item-title">Minimum number of characters</div>8 letters<br><div class="popover-item-title">Maximum number of characters</div>32 characters<br><div class="popover-item-title">Format</div>Including both alphabets and numbers.',
      popover_user_info_new_password_re: 'Please enter your password again.<hr><div class="popover-center">Rule</div><div class="popover-item-title">Format</div>Match Password',
      popover_user_setting_theme: 'You can choose the theme of your editor.',
      popover_user_setting_owner_public: 'You can choose your default owner setting.<br>Owner\'s public setting is managed for each clip.<hr><div class="popover-item-title">Private</div>Even if you publish or share a clip, your user name will not be displayed.<br><div class="popover-item-title">Public</div>Your user name will be displayed when you publish or share the clip.',
      popover_user_setting_clip_mode: 'You can choose your default clip sharing settings.<br>The clip sharing setting is managed for each clip.<hr><div class="popover-item-title">Private</div>Encrypt the code<br><div class="popover-item-title">Public</div>Person who knows shared link can view.<br><div class="popover-item-title">Share</div>People with shared links can edit at the same time.',

      popover_list_search_group: 'You can group clips.',
      popover_list_search_sort: 'You can sort clips.',
      popover_list_search_search: 'You can specify more than one blank separator.<br>You can specify the search target.<hr><div class="popover-center">Available phrases</div><div class="popover-item-title">name</div>File name<br><div class="popover-item-title">type</div>File type<br><div class="popover-item-title">tags</div>Tags<br><div class="popover-item-title">owner_public</div>Owner\'s public setting<br><div class="popover-item-title">clip_mode</div>clip sharing setting<br><div class="popover-item-title">created_at</div>Creation date<br><div class="popover-item-title">updated_at</div>Update date and time<hr><div class="popover-item-title">Example</div>name=test.txt<br>(Including test.txt in file name)',
      popover_list_search_search_type: 'This is the type of search when multiple items are specified with blank delimiters.<hr><div class="popover-item-title">OR</div>When one of them matches.<br><div class="popover-item-title">AND</div>When everything matches.<br><div class="popover-item-title">NOR</div>When one does not match.<br><div class="popover-item-title">NAND</div>When not all matches.<br><div class="popover-item-title">XOR</div>When only one match is made.',

      popover_clip_new_filename: 'Please enter the name of the clip.<hr>If you include an extension, the file type is automatically selected.',
      popover_clip_new_filetype: 'Please select a file type.<hr>Syntax highlighting according to file type is applied in the editor.',
      popover_clip_new_tags: 'Please specify tags arbitrarily.<br>You can specify more than one blank separator.',
      popover_clip_new_owner_public: 'Please select the owner\'s public setting of this clip.<hr><div class="popover-item-title">Private</div>Even if you publish or share a clip, your user name will not be displayed.<div class="popover-item-title">Public</div>Your user name will be displayed when you publish or share the clip.',
      popover_clip_new_clip_mode: 'Please select clip sharing setting of this clip.<hr><div class="popover-item-title">Private</div>Encrypt the code<br><div class="popover-item-title">Public</div>Person who knows shared link can view.<br><div class="popover-item-title">Share</div>People with shared links can edit at the same time.',

      popover_clip_setting_filename: 'You can change the name of the clip.<hr>If you include an extension, the file type is automatically selected.',
      popover_clip_setting_filetype: 'You can change the file type.<hr>Syntax highlighting according to file type is applied in the editor.',
      popover_clip_setting_tags: 'You can change tags.<br>You can specify more than one blank separator.',
      popover_clip_setting_owner_public: 'You can change the owner\'s public setting of this clip.<hr><div class="popover-item-title">Private</div>Even if you publish or share a clip, your user name will not be displayed.<br><div class="popover-item-title">Public</div>Your user name will be displayed when you publish or share the clip.',
      popover_clip_setting_clip_mode: 'You can change the clip sharing settings for this clip.<hr><div class="popover-item-title">Private</div>Encrypt the code<br><div class="popover-item-title">Public</div>Person who knows shared link can view.<br><div class="popover-item-title">Share</div>People with shared links can edit at the same time.',

      popover_clip_privilege_list: 'You can stop sharing this clip to the specified user.',

      popover_clip_history_history: 'You can restore this clip from the edit history.',

      clipweb_user_error_code: '{project} Error Code: {code}',
      clipweb_user_error_message: 'Message: {message}',
      clipweb_list_error_code: '{project} Error Code: {code}',
      clipweb_list_error_message: 'Message: {message}',
      clipweb_clip_error_code: '{project} Error Code: {code}',
      clipweb_clip_error_message: 'Message: {message}',
      clipweb_share_error_code: '{project} Error Code: {code}',
      clipweb_share_error_message: 'Message: {message}',
      clipweb_code_error_code: '{project} Error Code: {code}',
      clipweb_code_error_message: 'Message: {message}',
      flex_sqlite3_error_code: 'Flex Sqlite3 Error Code: {code}',
      flex_sqlite3_error_mode: 'Flex Sqlite3 Mode: {mode}',
      flex_sqlite3_error_message: 'Message: {message}',
    };
    this.ja = {
      language_name: '日本語',

      terms_of_service: `${Project.NAME} 利用規約`,
      terms_welcome_header: `${Project.NAME} へようこそ`,
      terms_welcome_content1: `${Project.NAME} （以下「本サービス」）をご利用いただきありがとうございます。本サービスは、ayatec（https://ayatec.jp/）（以下「当方」） が提供します。`,
      terms_welcome_content2: 'ユーザーは、本サービスを利用することにより、本規約に同意することになります。以下を注意してお読みください。',
      terms_header1: '第１条（適用）',
      terms_content1: '本規約は、ユーザーと当方との間の本サービスの利用に関わる一切の関係に適用されるものとします。',
      terms_header2: '第２条（利用登録）',
      terms_content2_1: '登録希望者が当方の定める方法によって利用登録を申請し、当方がこれを承認することによって、利用登録が完了するものとします。',
      terms_content2_2: '当方は、利用登録の申請者に以下の事由があると判断した場合、利用登録の申請を承認しないことがあり、その理由については一切の開示義務を負わないものとします。',
      terms_content2_2_1: '利用登録の申請に際して虚偽の事項を届け出た場合',
      terms_content2_2_2: '本規約に違反したことがある者からの申請である場合',
      terms_content2_2_3: 'その他、当方が利用登録を相当でないと判断した場合',
      terms_header3: '第３条（メールアドレスおよびパスワードの管理）',
      terms_content3_1: 'ユーザーは、自己の責任において、本サービスのメールアドレスおよびパスワードを管理するものとします。',
      terms_content3_2: 'ユーザーは、いかなる場合にも、メールアドレスおよびパスワードを第三者に譲渡または貸与することはできません。当方は、メールアドレスとパスワードの組み合わせが登録情報と一致してログインされた場合には、そのメールアドレスを登録しているユーザー自身による利用とみなします。',
      terms_header4: '第４条（禁止事項）',
      terms_content4: 'ユーザーは、本サービスの利用にあたり、以下の行為をしてはなりません。',
      terms_content4_1: '法令または公序良俗に違反する行為',
      terms_content4_2: '犯罪行為に関連する行為',
      terms_content4_3: '当方のサーバーまたはネットワークの機能を破壊したり、妨害したりする行為',
      terms_content4_4: '当方のサービスの運営を妨害するおそれのある行為',
      terms_content4_5: '他のユーザーに関する個人情報等を収集または蓄積する行為',
      terms_content4_6: '他のユーザーに成りすます行為',
      terms_content4_7: '当方のサービスに関連して、反社会的勢力に対して直接または間接に利益を供与する行為',
      terms_content4_8: 'その他、当方が不適切と判断する行為',
      terms_header5: '第５条（本サービスの提供の停止等）',
      terms_content5_1: '当方は、以下のいずれかの事由があると判断した場合、ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。',
      terms_content5_1_1: '本サービスにかかるコンピュータシステムの保守点検または更新を行う場合',
      terms_content5_1_2: '地震、落雷、火災、停電または天災などの不可抗力により、本サービスの提供が困難となった場合',
      terms_content5_1_3: 'コンピュータまたは通信回線等が事故により停止した場合',
      terms_content5_1_4: 'その他、当方が本サービスの提供が困難と判断した場合',
      terms_content5_2: '当方は、本サービスの提供の停止または中断により、ユーザーまたは第三者が被ったいかなる不利益または損害について、理由を問わず一切の責任を負わないものとします。',
      terms_header6: '第６条（利用制限および登録抹消）',
      terms_content6_1: '当方は、以下の場合には、事前の通知なく、ユーザーに対して、本サービスの全部もしくは一部の利用を制限し、またはユーザーとしての登録を抹消することができるものとします。',
      terms_content6_1_1: '本規約のいずれかの条項に違反した場合',
      terms_content6_1_2: 'その他、当方が本サービスの利用を適当でないと判断した場合',
      terms_content6_2: '当方は、本条に基づき当方が行った行為によりユーザーに生じた損害について、一切の責任を負いません。',
      terms_header7: '第７条（免責事項）',
      terms_content7: '当方は、本サービスに関して、ユーザーと他のユーザーまたは第三者との間において生じた取引、連絡または紛争等について一切責任を負いません。',
      terms_header8: '第８条（サービス内容の変更等）',
      terms_content8: '当方は、ユーザーに通知することなく、本サービスの内容を変更しまたは本サービスの提供を中止することができるものとし、これによってユーザーに生じた損害について一切の責任を負いません。',
      terms_header9: '第９条（利用規約の変更）',
      terms_content9: '当方は、必要と判断した場合には、ユーザーに通知することなくいつでも本規約を変更することができるものとします。',
      terms_header10: '第１０条（通知または連絡）',
      terms_content10: 'ユーザーと当方との間の通知または連絡は、当方の定める方法によって行うものとします。',
      terms_end: '以上',

      privacy_policy: 'プライバシーポリシー',
      privacy_welcome_content1: 'ayatec（https://ayatec.jp/）（以下「当方」） は、本ウェブサイト上で提供するサービス（以下,「本サービス」といいます。）におけるプライバシー情報の取扱いについて、以下のとおりプライバシーポリシー（以下、「本ポリシー」といいます。）を定めます。',
      privacy_header1: '第１条（プライバシー情報）',
      privacy_content1_1: 'プライバシー情報のうち「個人情報」とは、個人情報保護法にいう「個人情報」を指すものとし、生存する個人に関する情報であって、当該情報に含まれる氏名、生年月日、住所、電話番号、連絡先その他の記述等により特定の個人を識別できる情報を指します。',
      privacy_content1_2: 'プライバシー情報のうち「履歴情報および特性情報」とは、上記に定める「個人情報」以外のものをいい、ご利用いただいたサービスやご購入いただいた商品、ご覧になったページや広告の履歴、ご利用日時、ご利用の方法、ご利用環境、郵便番号や性別、職業、年齢、ユーザーのIPアドレス、クッキー情報、位置情報、端末の個体識別情報などを指します。',
      privacy_header2: '第２条（プライバシー情報の収集方法）',
      privacy_content2_1: '当方は、ユーザーが利用登録をする際にユーザー名、メールアドレスなどの情報をお尋ねすることがあります。',
      privacy_content2_2: '当方は、ユーザーについて、利用したサービス、閲覧したページ、チャット履歴、検索した検索キーワード、利用日時、利用方法、利用環境（携帯端末を通じてご利用の場合の当該端末の通信状態、利用に際しての各種設定情報なども含みます）、IPアドレス、などの履歴情報および特性情報を、ユーザーが当方のサービスを利用しまたはページを閲覧する際に収集します。',
      privacy_header3: '第３条（個人情報を収集・利用する目的）',
      privacy_content3: '当方が個人情報を収集・利用する目的は、以下のとおりです。',
      privacy_content3_1: 'ユーザーに自分の登録情報の閲覧や修正、利用状況の閲覧を行っていただくために、ユーザー名、メールアドレスなどの登録情報、利用されたサービスなどに関する情報を表示する目的',
      privacy_content3_2: 'ユーザーにお知らせや連絡、確認をするためにメールアドレスを利用する目的',
      privacy_content3_3: 'ユーザーが簡便にデータを入力できるようにするために、当方に登録されている情報を入力画面に表示させたり、ユーザーのご指示に基づいて他のサービスなどに転送したりする目的',
      privacy_content3_4: 'ユーザーからのお問い合わせに対応するために、お問い合わせ内容など当方がユーザーに対してサービスを提供するにあたって必要となる情報や、ユーザーのサービス利用状況、連絡先情報などを利用する目的',
      privacy_content3_5: '上記の利用目的に付随する目的',
      privacy_header4: '第４条（個人情報の第三者提供）',
      privacy_content4_1: '当方は、次に掲げる場合を除いて、あらかじめユーザーの同意を得ることなく、第三者に個人情報を提供することはありません。ただし、個人情報保護法その他の法令で認められる場合を除きます。',
      privacy_content4_1_1: '法令に基づく場合',
      privacy_content4_1_2: '人の生命、身体または財産の保護のために必要がある場合であって、本人の同意を得ることが困難であるとき',
      privacy_content4_1_3: '公衆衛生の向上または児童の健全な育成の推進のために特に必要がある場合であって、本人の同意を得ることが困難であるとき',
      privacy_content4_1_4: '国の機関もしくは地方公共団体またはその委託を受けた者が法令の定める事務を遂行することに対して協力する必要がある場合であって、本人の同意を得ることにより当該事務の遂行に支障を及ぼすおそれがあるとき',
      privacy_content4_1_5: '予め次の事項を告知あるいは公表をしている場合',
      privacy_content4_1_5_1: '利用目的に第三者への提供を含むこと',
      privacy_content4_1_5_2: '第三者に提供されるデータの項目',
      privacy_content4_1_5_3: '第三者への提供の手段または方法',
      privacy_content4_1_5_4: '本人の求めに応じて個人情報の第三者への提供を停止すること',
      privacy_content4_2: '前項の定めにかかわらず、次に掲げる場合は第三者には該当しないものとします。',
      privacy_content4_2_1: '当方が利用目的の達成に必要な範囲内において個人情報の取扱いの全部または一部を委託する場合',
      privacy_content4_2_2: '合併その他の事由による事業の承継に伴って個人情報が提供される場合',
      privacy_content4_2_3: '個人情報を特定の者との間で共同して利用する場合であって、その旨並びに共同して利用される個人情報の項目、共同して利用する者の範囲、利用する者の利用目的および当該個人情報の管理について責任を有する者の氏名または名称について、あらかじめ本人に通知し、または本人が容易に知り得る状態に置いているとき',
      privacy_header5: '第５条（個人情報の開示）',
      privacy_content5_1: '当方は、本人から個人情報の開示を求められたときは、本人に対し、これを開示します。ただし、開示することにより次のいずれかに該当する場合は、その全部または一部を開示しないこともあります。',
      privacy_content5_1_1: '本人または第三者の生命、身体、財産その他の権利利益を害するおそれがある場合',
      privacy_content5_1_2: '当方の業務の適正な実施に著しい支障を及ぼすおそれがある場合',
      privacy_content5_1_3: 'その他法令に違反することとなる場合',
      privacy_content5_2: '前項の定めにかかわらず、履歴情報および特性情報などの個人情報以外の情報については、原則として開示いたしません。',
      privacy_header6: '第６条（個人情報の訂正）',
      privacy_content6: 'ユーザーは、当方の保有する自己の個人情報が誤った情報である場合には、当方が定める手続きにより、当方に対して個人情報の訂正することができます。',
      privacy_header7: '第７条（個人情報の利用停止等）',
      privacy_content7: '当方は、本人から、個人情報が、利用目的の範囲を超えて取り扱われているという理由、または不正の手段により取得されたものであるという理由により、その利用の停止または消去（以下、「利用停止等」といいます。）を求められた場合には、必要な調査を行い、その結果に基づき、個人情報の利用停止等を行い、その旨本人に通知します。ただし、個人情報の利用停止等に多額の費用を有する場合その他利用停止等を行うことが困難な場合であって、本人の権利利益を保護するために必要なこれに代わるべき措置をとれる場合は、この代替策を講じます。',
      privacy_header8: '第８条（プライバシーポリシーの変更）',
      privacy_content8_1: '本ポリシーの内容は、ユーザーに通知することなく、変更することができるものとします。',
      privacy_content8_2: '当方が別途定める場合を除いて、変更後のプライバシーポリシーは、本ウェブサイトに掲載したときから効力を生じるものとします。',
      privacy_header9: '第９条（プライバシーポリシーの変更）',
      privacy_content9: '本ポリシーの内容は、ユーザーに通知することなく、変更することができるものとします。',
      privacy_end: '以上',

      please_feedback: 'clipwebへのフィードバックをお願いします。',
      feedback_message: 'バグ報告だけでなく、あると良いと思う機能や感想なども募集しております。',
      feedback_received_data: 'フィードバック内容のみが clipwebの管理者 に送信されます。',
      thank_you_feedback: 'フィードバックのご送信ありがとうございます。',

      user: 'ユーザー',
      username: 'ユーザー名',
      email_address: 'メールアドレス',
      password: 'パスワード',
      password_hash: 'パスワードハッシュ',
      crypto_hash: '暗号化用ハッシュ',
      last_search: '前回の検索文字列',
      last_search_type: '前回の検索タイプ',
      last_search_group: '前回の検索グループ',
      last_search_sort: '前回の検索ソート',
      history_clip: 'クリップの履歴',
      language: '言語',
      auto_login: '自動ログイン',
      password_confirm: 'パスワードの確認',
      new_password: '新しいパスワード',
      avatar: 'アバター',
      theme: 'テーマ',
      default_owner_public: 'デフォルトのオーナー公開設定',
      default_clip_mode: 'デフォルトのクリップ共有設定',
      owner_public: 'オーナー公開設定',
      clip_mode: 'クリップ共有設定',
      using_gravatar: '{gravatar} を利用しています。',

      filename: 'ファイル名',
      filetype: 'ファイル種別',

      clip: 'クリップ',
      clips: 'クリップ',

      list: '一覧',
      history: '履歴',
      help: 'ヘルプ',

      status_login: 'ログインステータス',
      terms_agree: '利用規約の同意',

      register: '登録',
      login: 'ログイン',
      logout: 'ログアウト',
      setting: '設定',
      info: '情報',

      license: 'ライセンス',
      column: 'カラム',
      value: '値',
      none: 'なし',
      all: '全て',
      open: '開く',
      show: '閲覧',
      view: '閲覧',
      unknown: '不明',
      name: '名前',
      yes: 'はい',
      no: 'いいえ',
      on: 'オン',
      off: 'オフ',
      save: '保存',
      access: 'アクセス',
      new_create: '新規作成',
      clip_new_create: 'クリップの新規作成',
      clip_info: 'クリップ情報',
      share_list: '共有リスト',
      privilege_users_list: '権限リスト',
      clip_history: 'クリップ履歴',
      start: '開始',
      restart: '再開',
      initial: '初期',
      init: '初期',
      reload: '再読込',
      encryption: '暗号化',
      update: '更新',
      create: '作成',
      new: '新規',
      edit: '編集',
      delete: '削除',
      accept: '確認',
      agree: '同意する',
      close: '閉じる',
      feedback: 'フィードバック',
      report: '報告',
      content: '内容',
      send: '送信',
      search: '検索',
      search_string: '検索文字列',
      search_query: 'クエリ',
      search_type: 'タイプ',
      group: 'グループ',
      sort: '並び替え',
      type: '種別',
      tag: 'タグ',
      tags: 'タグ',
      owner: 'オーナー',
      created_at: '作成日時',
      updated_at: '更新日時',
      private: '非公開',
      public: '公開',
      share: '共有',
      light: 'ライト',
      dark: 'ダーク',

      within_1_week: '１週間以内',
      within_1_month: '１ヶ月以内',
      within_3_month: '３ヶ月以内',
      within_6_month: '６ヶ月以内',
      within_1_year: '１年以内',
      over_1_year_ago: '１年以上前',

      header_user_register: 'ユーザー登録',
      header_user_login: 'ログイン',
      header_user_logout: 'ログアウト',
      header_user_leaving: 'ユーザー削除',
      header_user_setting: 'ユーザー設定',
      header_user_info: 'ユーザー情報',

      header_list_search: 'クリップ一覧',

      header_clip_new: '新規クリップ',
      header_clip_setting: 'クリップ設定',
      header_clip_privilege: 'クリップ権限',
      header_clip_history: 'クリップ履歴',

      header_code_editor: null,

      loading_header_user_register: 'clipweb に登録中',
      loading_header_user_login: 'ログイン中',
      loading_header_user_logout: 'ログアウト中',
      loading_header_user_leaving: 'ユーザーを削除中',
      loading_header_user_setting: 'ユーザー設定を保存中',
      loading_header_user_info: 'ユーザー情報を保存中',

      loading_header_list_search: 'クリップ一覧を取得中',

      loading_header_clip_new: 'クリップを作成中',
      loading_header_clip_load: 'クリップの情報を取得中',
      loading_header_clip_setting: 'クリップを設定中',
      loading_header_clip_privilege: 'クリップの権限を取得中',
      loading_header_clip_ban: 'クリップの権限を削除中',
      loading_header_clip_history: 'クリップの履歴を取得中',
      loading_header_clip_delete: 'クリップを削除中',

      loading_header_code_load: 'コードを読み込み中',

      user_registered: 'ユーザーを登録しました。',
      user_logined: 'ログインしました。',
      user_logouted: 'ログアウトしました。',
      user_update_info: 'ユーザー情報を更新しました。',
      user_update_setting: 'ユーザー設定を更新しました。',

      clip_list_got: 'クリップ一覧を取得しました。',
      created_new_clip: '新しいクリップを作成しました。',
      updated_clip_setting: 'クリップの設定を更新しました。',
      deleted_clip: 'クリップを削除しました。',
      shared_clip: 'クリップを共有しました。',
      stopped_share_to_user: '{ban_username}への共有を停止しました。',

      saved_clip: 'クリップを保存しました。',
      downloaded_clip: 'クリップをダウンロードしました。',

      please_email_auth: 'メール認証をしてください。',
      userdata_clear: 'ユーザデータの削除',
      userdata_clear_confirm: 'ブラウザに保存されているユーザーデータを削除しますか？',
      delete_clip: 'クリップの削除',
      delete_clip_confirm: 'クリップを削除してもよろしいですか？',
      share_clip: 'クリップの共有',
      share_clip_message: 'このURLを共有してください。',
      share_clip_sns: 'SNSで共有できます。',
      stop_share_user: '共有の停止',
      stop_share_user_confirm: 'このユーザーへの共有を停止しますか？',
      concurrent_editing_stop: '同時編集の一時停止',
      close_to_start_concurrent_editing: 'この画面を閉じると、同時編集が再開されます。',

      copied: 'コピーしました。',
      copied_share_link: '共有リンクをコピーしました。',

      need_login_to_share: '共有するにはログインが必要です。',
      please_all_inputs_correctly: 'すべての項目を正しく入力してください。',
      please_inputs_correctly: '正しく入力してください。',
      please_selects_correctly: '正しく選択してください。',
      password_dont_match: 'パスワードが一致しません。',

      username_alreay_exist: 'すでに存在するユーザー名です。',
      email_address_alreay_exist: 'すでに存在するメールアドレスです。',
      hash_alreay_exist: 'ユーザー情報が構築できません。もう一度お試しください。',
      email_password_incorrect: 'メールアドレスとパスワードの組み合わせが間違っています。',
      password_incorrect: 'パスワードが間違っています。',
      user_not_found: 'ユーザーデータが見つかりません。',
      clip_not_exists: 'クリップが見つかりません。',
      owner_not_exists: 'クリップのオーナーが見つかりません。',
      corrupt_userdata: 'ユーザーデータが破損しています。管理者までご確認ください。',
      corrupt_clipdata: 'クリップデータが破損しています。管理者までご確認ください。',
      permission_denied: '権限がありません。',
      permission_denied_or_clip_not_found: '権限がないか、クリップが見つかりません。',
      failed_update_share: 'シェア日時の更新に失敗しました。',

      failed_to_register: '登録できませんでした。',
      failed_to_login: 'ログインに失敗しました。',
      failed_to_logout: 'ログアウトに失敗しました。',
      failed_to_save_setting: 'ユーザー設定の保存に失敗しました。',
      failed_to_save_info: 'ユーザー情報の保存に失敗しました。',

      failed_to_get_clip_list: 'クリップ一覧の取得に失敗しました。',
      failed_to_create_new_clip: '新しいクリップの作成に失敗しました。',

      failed_to_open_clip_setting: 'クリップの設定を開くことができませんでした。',
      failed_to_load_clip_setting: 'クリップの設定を読み込むことができませんでした。',
      failed_to_update_clip_setting: 'クリップの設定の更新に失敗しました。',
      failed_to_setting_clip_setting: 'クリップの設定の更新に失敗しました。',
      failed_to_load_clip_privilege: 'クリップの権限の取得に失敗しました。',
      failed_to_load_clip_history: 'クリップの履歴の取得に失敗しました。',
      failed_to_delete_clip: 'クリップの削除に失敗しました。',
      failed_to_get_share_clip: 'クリップの共有に失敗しました。',
      failed_to_stop_share: '共有の停止に失敗しました。',

      failed_to_load_code: 'クリップの読み込みに失敗しました。',
      failed_to_save_code: 'クリップの保存に失敗しました。',
      failed_to_download_code: 'クリップのダウンロードに失敗しました。',
      failed_to_sync_code: 'クリップの同期に失敗しました。',
      failed_to_connect_chat: 'チャットの接続に失敗しました。',

      failed_connect_to_server: 'clipwebサーバーとの通信に失敗しました。',
      server_not_working: 'clipwebサーバーが正常に動作していません。',

      popover_user_register_username: 'clipwebに登録するユーザー名<hr><div class="popover-center">ルール</div><div class="popover-item-title">最小文字数</div>３文字<br><div class="popover-item-title">最大文字数</div>３２文字',
      popover_user_register_email: 'clipwebに登録するメールアドレス<hr><div class="popover-center">ルール</div><div class="popover-item-title">パターン</div>メールアドレス形式',
      popover_user_register_password: 'ログイン時に必要なパスワード<hr><div class="popover-center">ルール</div><div class="popover-item-title">最小文字数</div>８文字<br><div class="popover-item-title">最大文字数</div>３２文字<br><div class="popover-item-title">パターン</div>アルファベットと数字を両方含む',
      popover_user_register_password_re: 'もう一度パスワードを入力してください。<hr><div class="popover-center">ルール</div><div class="popover-item-title">パターン</div>パスワードと一致',
      popover_user_login_email: 'clipwebに登録したメールアドレス',
      popover_user_login_password: 'clipwebに登録したパスワード',
      popover_user_login_auto: 'チェックを入れると、このウェブブラウザからは自動でログインします。<hr><div class="popover-item-title">※注意</div>家族などと共有しているパソコンでは使用しないでください。',
      popover_user_logout_username: 'あなたのユーザー名',
      popover_user_info_avatar: 'アバターには <a href="https://gravatar.com/" target="blank">Gravatar</a> を利用しています。<br>メールアドレスに関連付けられたアバターが表示されます。',
      popover_user_info_username: 'あなたのユーザー名を変更できます。<hr><div class="popover-center">ルール</div><div class="popover-item-title">最小文字数</div>３文字<br><div class="popover-item-title">最大文字数</div>３２文字',
      popover_user_info_email: 'あなたのメールアドレスを変更できます。<hr><div class="popover-center">ルール</div><div class="popover-item-title">パターン</div>メールアドレス形式',
      popover_user_info_old_password: 'ユーザー情報の変更には、パスワード認証が必要です。',
      popover_user_info_new_password: 'ログインに必要なパスワードを変更できます。<hr><div class="popover-center">ルール</div><div class="popover-item-title">最小文字数</div>８文字<br><div class="popover-item-title">最大文字数</div>３２文字<br><div class="popover-item-title">パターン</div>アルファベットと数字を両方含む',
      popover_user_info_new_password_re: 'もう一度パスワードを入力してください。<hr><div class="popover-center">ルール</div><div class="popover-item-title">パターン</div>パスワードと一致',
      popover_user_setting_theme: 'あなたのエディタのテーマを選択できます。',
      popover_user_setting_owner_public: 'あなたのデフォルトのオーナー公開設定を選択できます。<br>オーナー公開設定は、クリップごとに管理されています。<hr><div class="popover-item-title">非公開</div>クリップを公開や共有しても、あなたのユーザー名は表示されません。<br><div class="popover-item-title">公開</div>クリップを公開や共有した際に、あなたのユーザー名が表示されます。',
      popover_user_setting_clip_mode: 'あなたのデフォルトのクリップ共有設定を選択できます。<br>クリップ共有設定は、クリップごとに管理されています。<hr><div class="popover-item-title">非公開</div>コードを暗号化<br><div class="popover-item-title">公開</div>共有リンクを知っている人が閲覧可能<br><div class="popover-item-title">共有</div>共有リンクを知っている人が同時編集可能',

      popover_list_search_group: 'クリップをグループに分けることができます。',
      popover_list_search_sort: 'クリップを並び替えることができます。',
      popover_list_search_search: '空白区切りで複数指定できます。<br>検索対象を指定できます。<hr><div class="popover-center">使用可能語句</div><div class="popover-item-title">name</div>ファイル名<br><div class="popover-item-title">type</div>ファイル種別<br><div class="popover-item-title">tags</div>タグ<br><div class="popover-item-title">owner_public</div>オーナー公開設定<br><div class="popover-item-title">clip_mode</div>クリップ共有設定<br><div class="popover-item-title">created_at</div>作成日時<br><div class="popover-item-title">updated_at</div>更新日時<hr><div class="popover-item-title">例</div>name=test.txt<br>（ファイル名にtest.txtを含む）',
      popover_list_search_search_type: '空白区切りで複数指定した際の検索のタイプです。<hr><div class="popover-item-title">OR</div>いずれかがマッチしたとき。<br><div class="popover-item-title">AND</div>全てがマッチしたとき。<br><div class="popover-item-title">NOR</div>いずれかがマッチしないとき。<br><div class="popover-item-title">NAND</div>全てがマッチしないとき。<br><div class="popover-item-title">XOR</div>一つのみマッチしたとき。',

      popover_clip_new_filename: 'クリップの名前を入力してください。<hr>拡張子を含めると、ファイル種別が自動で選択されます。',
      popover_clip_new_filetype: 'ファイル種別を選択してください。<hr>エディタで、ファイル種別に応じたシンタックスハイライトが適用されます。',
      popover_clip_new_tags: '任意でタグを指定してください。<br>空白区切りで複数指定できます。',
      popover_clip_new_owner_public: 'このクリップのオーナー公開設定を選択してください。<hr><div class="popover-item-title">非公開</div>クリップを公開や共有しても、あなたのユーザー名は表示されません。<div class="popover-item-title">公開</div>クリップを公開や共有した際に、あなたのユーザー名が表示されます。',
      popover_clip_new_clip_mode: 'このクリップのクリップ共有設定を選択してください。<hr><div class="popover-item-title">非公開</div>コードを暗号化<br><div class="popover-item-title">公開</div>共有リンクを知っている人が閲覧可能<br><div class="popover-item-title">共有</div>共有リンクを知っている人が同時編集可能',

      popover_clip_setting_filename: 'クリップの名前を変更できます。<hr>拡張子を含めると、ファイル種別が自動で選択されます。',
      popover_clip_setting_filetype: 'ファイル種別を変更できます。<hr>エディタで、ファイル種別に応じたシンタックスハイライトが適用されます。',
      popover_clip_setting_tags: 'タグを変更できます。<br>空白区切りで複数指定できます。',
      popover_clip_setting_owner_public: 'このクリップのオーナー公開設定を変更できます。<hr><div class="popover-item-title">非公開</div>クリップを公開や共有しても、あなたのユーザー名は表示されません。<br><div class="popover-item-title">公開</div>クリップを公開や共有した際に、あなたのユーザー名が表示されます。',
      popover_clip_setting_clip_mode: 'このクリップのクリップ共有設定を変更できます。<hr><div class="popover-item-title">非公開</div>コードを暗号化<br><div class="popover-item-title">公開</div>共有リンクを知っている人が閲覧可能<br><div class="popover-item-title">共有</div>共有リンクを知っている人が同時編集可能',

      popover_clip_privilege_list: 'このクリップの、指定したユーザーへの共有を停止することができます。',

      popover_clip_history_history: 'このクリップを編集履歴から復元することができます。',

      clipweb_user_error_code: '{project} エラーコード： {code}',
      clipweb_user_error_message: 'メッセージ： {message}',
      clipweb_list_error_code: '{project} エラーコード： {code}',
      clipweb_list_error_message: 'メッセージ： {message}',
      clipweb_clip_error_code: '{project} エラーコード： {code}',
      clipweb_clip_error_message: 'メッセージ： {message}',
      clipweb_share_error_code: '{project} エラーコード： {code}',
      clipweb_share_error_message: 'メッセージ： {message}',
      clipweb_code_error_code: '{project} エラーコード： {code}',
      clipweb_code_error_message: 'メッセージ： {message}',
      flex_sqlite3_error_code: 'Flex Sqlite3 エラーコード： {code}',
      flex_sqlite3_error_mode: 'Flex Sqlite3 モード： {mode}',
      flex_sqlite3_error_message: 'メッセージ： {message}',
    };
    this.zh = {
      language_name: '中文',
    };
    this.fl = {
      language_name: 'Français',
    };
    this.ru = {
      language_name: 'Русский язык',
    };
    this.ko = {
      language_name: '한국',
    };
    this.de = {
      language_name: 'Deutsch',
    };
    this.it = {
      language_name: 'italiano',
    };
    this.es = {
      language_name: 'Español',
    };
    this.ar = {
      language_name: 'عربى',
    };
    this.eo = {
      language_name: 'Esperanto',
    };
    this.la = {
      language_name: 'Latine',
    };
    this.ms = {
      language_name: 'Melayu',
    };
    this.el = {
      language_name: 'Ελληνικά',
    };
  }
}
